# install.packages("devtools")
# devtools::install_github("ha0ye/rEDM")
library(lubridate);
library(rEDM);
library(tidyr)
library(ggpubr);
library(reshape2);
library(ggplot2);
library(gplots)
library(RColorBrewer);
library(readxl);
library(lubridate);
library(gtable)
library(reshape);
library(scales);
library(showtext);
library(dplyr);
library(Kendall);
library(psych);
library(ggrepel)
library(tsModel);
library(tidyverse);
library(lubridate);
library(mgcv);
library(MASS);
library(splines);
library(dlnm);
library(showtext);
library(car);
library(R330);
library(boot);
library(ggsignif);
library(poolr);
library(corrplot)
sessionInfo()
