mytheme <- theme_minimal()+
  theme(
    #panel.grid.major.x=element_blank(),
    panel.grid.minor.x=element_blank(),
    #panel.grid.major.y=element_blank(),
    panel.grid.minor.y=element_blank(),
    # plot.title=element_text(size=12, vjust = 0.5, hjust = 0.5),
    legend.position = c("bottom"),
    legend.key.size = unit(0.25,"cm"),
    legend.key.width = unit(1,"cm"),
    legend.key.height  = unit(0.5,"cm"),
    #legend.spacing.x = unit(1, 'cm'),
    legend.margin = margin(0, 0, 0, 0),
    legend.background = element_rect(fill=NA, size=0,color=NA),
    legend.text=element_text(size=20),
    legend.title=element_text(face="bold",size=20),
    axis.line.y=element_line(linetype=1,color='black',size=0.5),
    axis.line.x=element_line(linetype=1,color='black',size=0.5),
    axis.ticks = element_line(linetype=2,color='black'),
    panel.grid=element_line(linetype=1,color='grey'),
    plot.title = element_text(hjust = 0.5,size=22, face = "bold"),
    axis.title.y.left = element_text(size = 20,color="black",vjust=0,face = "bold"),
    axis.title.y.right =element_text(size = 20,color="black",vjust=0,angle=90),
    axis.title.x = element_text(size = 20, color="black",face = "bold", vjust = 0),
    axis.text.y.left = element_text(size = 20,color="black",vjust = 0.5,angle = 0),
    axis.text.y.right = element_text(size = 20,color="black",vjust = 0.5,angle = 0),
    axis.text.x = element_text(size = 20, color="black",vjust = 0.5, angle = 0),
    axis.ticks.length=unit(0.15,"cm"),
    axis.ticks.y=element_line(color="black",size=.5),
    axis.ticks.x=element_line(color="black",size=.5),
    plot.margin=unit(c(0.5,0.5,0.5,0.5),'lines'),
    panel.border = element_rect(colour = "black", fill=NA, size=1)
  )

